removed contract as we have errors while testing
~~~
16:54:52.863 [main] ERROR o.s.test.context.TestContextManager - Caught exception while allowing TestExecutionListener [org.springframework.test.context.support.DependencyInjectionTestExecutionListener@6567de86] to prepare test instance [com.sdl.delivery.dxa.modelservice.transformer.TransformationIntegrationTest@5350a926]
java.lang.IllegalStateException: Failed to load ApplicationContext
	at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:125)
	at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:108)
	at org.springframework.test.context.support.DependencyInjectionTestExecutionListener.injectDependencies(DependencyInjectionTestExecutionListener.java:118)
...
Caused by: java.lang.IllegalStateException: Failed to introspect Class [com.sdl.delivery.dxa.modelservice.linking.TridionLinkResolver] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@5a07e868]
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:760)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:725)
	at org.springframework.util.ReflectionUtils.doWithFields(ReflectionUtils.java:710)
...
Caused by: java.lang.NoClassDefFoundError: com/sdl/webapp/common/api/content/LinkResolver$AjcClosure1
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3139)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2262)
	at org.springframework.util.ReflectionUtils.getDeclaredFields(ReflectionUtils.java:755)
~~~